name: Annoy

on:
  push:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
        os: ["ubuntu-20.04", "macos-latest", "windows-latest"]
        unsigned: [true, false]

    steps:
      - uses: actions/checkout@v3 # Pull the repository
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Use unsigned indices
        if: ${{ matrix.unsigned }}
        run: |
          cat src/annoymodule.cc | sed "s/.*\(#define ANNOYLIB_UNSIGNED_INDEX\)/\1/" > .tmp
          cmp .tmp src/annoymodule.cc && exit 1 # ensure a change was actually made.
          mv .tmp src/annoymodule.cc

      - run: pip install .
      - run: pip install h5py numpy pytest
      - run: pytest -v
